export interface Fields {
    [index: string]: any
    accept_friends_count: number[]
    accept_friends_on_farm: boolean
    action_interval: any[]
    ads_friends_count: number
    ads_invite_friends_day_start: number
    ads_refriend_friends: boolean
    capmonster_api_key: number
    capthca_type: string
    change_proxy_on_invalid: boolean
    change_proxy_on_invalid_checkpoint: boolean
    chat_bot: boolean
    chat_bot_threads: number
    chat_bot_web: boolean
    chat_bot_web_threads: number
    check_black_list_names: boolean
    check_white_list_names: boolean
    checkpoint_status: boolean
    checkpoint_threads_count: number
    day_to_create_fan_page: number
    day_to_start_inviter: number
    emulate_mouse: boolean
    fakes_count: any[]
    fan_page: boolean
    fan_page_fill_from_lifehacker: boolean
    fan_page_lifehacker_postcount: number
    fan_page_names: string
    farm_status: boolean
    farm_threads_count: number
    fb_authorization: boolean
    fb_authorization_threads: number
    fb_feed_autoposting: boolean
    fb_feed_autoposting_threads: number
    fb_friends_aproove_requests: boolean
    fb_friends_aproove_requests_threads: number
    fb_worm_bm: boolean
    fb_worm_bm_threads: number
    friends_aproove: boolean
    friends_aproove_threads: number
    friends_count_to_donar: number
    groups_for_parsing_target_audience: string
    invite_man: boolean
    invite_woman: boolean
    inviter: boolean
    inviter_geo: string
    links_to_invite: string
    login_to_sites: boolean
    lts_count: number
    lts_sites: string
    lts_start_day: number
    often_to_run: any[]
    often_to_run_worm: any[]
    post_from_sites: boolean
    relink_to_desktop_ua: boolean
    relink_to_desktop_ua_day_start: number
    remove_phone: boolean
    spam_bot_enable: boolean
    spam_bot_how_often_run: number
    spam_bot_treads: number
    turn_off_profile: boolean
    turn_off_profile_after_days: number
    visit_sites_status: boolean
    visited_sites_count: any[]
    worm_status: boolean
    worm_threads_count: number
}
